import localFont from "next/font/local";
import "./globals.css";
import Header from "@/ui/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-t from-teal-100/25 via-teal-100/20 to-teal-100/15`}
      >
        <Header />

        <main className="container mx-auto xl:w-6/7 my-10 p-2">{children}</main>
      </body>
    </html>
  );
}
